FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
COPY index.html ./
COPY tsconfig.json tsconfig.app.json tsconfig.node.json ./
COPY vite.config.ts ./
COPY public ./public
COPY src ./src

RUN npm install

EXPOSE 4173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
